import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import MobileNav from "@/components/MobileNav";
import logo from "../logo.png";
import Image from "next/image";
import { CameraIcon, HomeIcon, LayoutGridIcon, SearchIcon, UserIcon } from "lucide-react";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Theme>
          <div className="flex">
            <div className="hidden lg:block p-4 w-48 shadow-md shadow-gray-400">
              <div className="top-0 sticky">
                <Image className="w-full" src={logo} alt="" />
                <div className="ml-1 inline-flex flex-col gap-4 mt-4 *:flex *:items-center *:gap-2">
                  <Link href="/">
                    <HomeIcon />
                    Home
                  </Link>
                  <Link href="/search">
                    <SearchIcon />
                    Search
                  </Link>
                  <Link href="/browse">
                    <LayoutGridIcon />
                    Browse
                  </Link>
                  <Link href="/profile">
                    <UserIcon />
                    Profile
                  </Link>
                  <Link href="/create">
                    <CameraIcon />
                    Create
                  </Link>
                </div>
              </div>
              
            </div>
            <div className="p-4 flex justify-around w-full">
              <div>
                {children}
              </div>
            </div>
          </div>
          <MobileNav />
        </Theme>
      </body>
    </html>
  );
}
